import os
from collections.abc import Iterable, Mapping, Sequence
from typing import Any, AnyStr, ClassVar, Literal, SupportsFloat, Union, overload

import numpy as np
from _typeshed import Incomplete
from typing_extensions import CapsuleType, disjoint_base

CONST: Term
EventNames: dict
MAJOR: int
MINOR: int
Operator: Op
PATCH: int
PY_SCIP_CALL: Incomplete
StageNames: dict
TYPE_CHECKING: bool
_SCIP_BOUNDTYPE_TO_STRING: dict
_core_dot: Incomplete
_core_dot_2d: Incomplete
_core_sum: Incomplete
buildGenExprObj: Incomplete
cos: Incomplete
exp: Incomplete
expr_to_array: Incomplete
expr_to_nodes: Incomplete
is_memory_freed: Incomplete
log: Incomplete
print_memory_in_use: Incomplete
quickprod: Incomplete
quicksum: Incomplete
readStatistics: Incomplete
sin: Incomplete
sqrt: Incomplete
str_conversion: Incomplete
value_to_array: Incomplete

@disjoint_base
class Benders:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def benderscreatesub(self, probnumber: Incomplete) -> Incomplete: ...
    def bendersexit(self) -> Incomplete: ...
    def bendersexitpre(self) -> Incomplete: ...
    def bendersexitsol(self) -> Incomplete: ...
    def bendersfree(self) -> Incomplete: ...
    def bendersfreesub(self, probnumber: Incomplete) -> Incomplete: ...
    def bendersgetvar(
        self, variable: Incomplete, probnumber: Incomplete
    ) -> Incomplete: ...
    def bendersinit(self) -> Incomplete: ...
    def bendersinitpre(self) -> Incomplete: ...
    def bendersinitsol(self) -> Incomplete: ...
    def benderspostsolve(
        self,
        solution: Incomplete,
        enfotype: Incomplete,
        mergecandidates: Incomplete,
        npriomergecands: Incomplete,
        checkint: Incomplete,
        infeasible: Incomplete,
    ) -> Incomplete: ...
    def benderspresubsolve(
        self, solution: Incomplete, enfotype: Incomplete, checkint: Incomplete
    ) -> Incomplete: ...
    def benderssolvesub(
        self, solution: Incomplete, probnumber: Incomplete
    ) -> Incomplete: ...
    def benderssolvesubconvex(
        self, solution: Incomplete, probnumber: Incomplete, onlyconvex: Incomplete
    ) -> Incomplete: ...

@disjoint_base
class Benderscut:
    benders: Incomplete
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def benderscutexec(
        self, solution: Incomplete, probnumber: Incomplete, enfotype: Incomplete
    ) -> Incomplete: ...
    def benderscutexit(self) -> Incomplete: ...
    def benderscutexitsol(self) -> Incomplete: ...
    def benderscutfree(self) -> Incomplete: ...
    def benderscutinit(self) -> Incomplete: ...
    def benderscutinitsol(self) -> Incomplete: ...

@disjoint_base
class BoundChange:
    def __init__(self) -> None: ...
    def getBoundchgtype(self) -> Incomplete: ...
    def getBoundtype(self) -> Incomplete: ...
    def getNewBound(self) -> Incomplete: ...
    def getVar(self) -> Incomplete: ...
    def isRedundant(self) -> Incomplete: ...

@disjoint_base
class Branchrule:
    model: Incomplete
    def __init__(self) -> None: ...
    def branchexecext(self, allowaddcons: Incomplete) -> Incomplete: ...
    def branchexeclp(self, allowaddcons: Incomplete) -> Incomplete: ...
    def branchexecps(self, allowaddcons: Incomplete) -> Incomplete: ...
    def branchexit(self) -> Incomplete: ...
    def branchexitsol(self) -> Incomplete: ...
    def branchfree(self) -> Incomplete: ...
    def branchinit(self) -> Incomplete: ...
    def branchinitsol(self) -> Incomplete: ...

@disjoint_base
class Column:
    data: Incomplete
    def __init__(self) -> None: ...
    def getAge(self) -> Incomplete: ...
    def getBasisStatus(self) -> Incomplete: ...
    def getLPPos(self) -> Incomplete: ...
    def getLb(self) -> Incomplete: ...
    def getObjCoeff(self) -> Incomplete: ...
    def getPrimsol(self) -> Incomplete: ...
    def getUb(self) -> Incomplete: ...
    def getVar(self) -> Incomplete: ...
    def isIntegral(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class ColumnExact:
    data: Incomplete
    def __init__(self) -> None: ...

@disjoint_base
class Conshdlr:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def consactive(self, constraint: Incomplete) -> Incomplete: ...
    def conscheck(
        self,
        constraints: Incomplete,
        solution: Incomplete,
        checkintegrality: Incomplete,
        checklprows: Incomplete,
        printreason: Incomplete,
        completely: Incomplete,
    ) -> Incomplete: ...
    def conscopy(self) -> Incomplete: ...
    def consdeactive(self, constraint: Incomplete) -> Incomplete: ...
    def consdelete(self, constraint: Incomplete) -> Incomplete: ...
    def consdelvars(self, constraints: Incomplete) -> Incomplete: ...
    def consdisable(self, constraint: Incomplete) -> Incomplete: ...
    def consenable(self, constraint: Incomplete) -> Incomplete: ...
    def consenfolp(
        self,
        constraints: Incomplete,
        nusefulconss: Incomplete,
        solinfeasible: Incomplete,
    ) -> Incomplete: ...
    def consenfops(
        self,
        constraints: Incomplete,
        nusefulconss: Incomplete,
        solinfeasible: Incomplete,
        objinfeasible: Incomplete,
    ) -> Incomplete: ...
    def consenforelax(
        self,
        solution: Incomplete,
        constraints: Incomplete,
        nusefulconss: Incomplete,
        solinfeasible: Incomplete,
    ) -> Incomplete: ...
    def consexit(self, constraints: Incomplete) -> Incomplete: ...
    def consexitpre(self, constraints: Incomplete) -> Incomplete: ...
    def consexitsol(
        self, constraints: Incomplete, restart: Incomplete
    ) -> Incomplete: ...
    def consfree(self) -> Incomplete: ...
    def consgetdivebdchgs(self) -> Incomplete: ...
    def consgetnvars(self, constraint: Incomplete) -> Incomplete: ...
    def consgetpermsymgraph(self) -> Incomplete: ...
    def consgetsignedpermsymgraph(self) -> Incomplete: ...
    def consgetvars(self, constraint: Incomplete) -> Incomplete: ...
    def consinit(self, constraints: Incomplete) -> Incomplete: ...
    def consinitlp(self, constraints: Incomplete) -> Incomplete: ...
    def consinitpre(self, constraints: Incomplete) -> Incomplete: ...
    def consinitsol(self, constraints: Incomplete) -> Incomplete: ...
    def conslock(
        self,
        constraint: Incomplete,
        locktype: Incomplete,
        nlockspos: Incomplete,
        nlocksneg: Incomplete,
    ) -> Incomplete: ...
    def consparse(self) -> Incomplete: ...
    def conspresol(
        self,
        constraints: Incomplete,
        nrounds: Incomplete,
        presoltiming: Incomplete,
        nnewfixedvars: Incomplete,
        nnewaggrvars: Incomplete,
        nnewchgvartypes: Incomplete,
        nnewchgbds: Incomplete,
        nnewholes: Incomplete,
        nnewdelconss: Incomplete,
        nnewaddconss: Incomplete,
        nnewupgdconss: Incomplete,
        nnewchgcoefs: Incomplete,
        nnewchgsides: Incomplete,
        result_dict: Incomplete,
    ) -> Incomplete: ...
    def consprint(self, constraint: Incomplete) -> Incomplete: ...
    def consprop(
        self,
        constraints: Incomplete,
        nusefulconss: Incomplete,
        nmarkedconss: Incomplete,
        proptiming: Incomplete,
    ) -> Incomplete: ...
    def consresprop(self) -> Incomplete: ...
    def conssepalp(
        self, constraints: Incomplete, nusefulconss: Incomplete
    ) -> Incomplete: ...
    def conssepasol(
        self, constraints: Incomplete, nusefulconss: Incomplete, solution: Incomplete
    ) -> Incomplete: ...
    def constrans(self, sourceconstraint: Incomplete) -> Incomplete: ...

@disjoint_base
class Constant(GenExpr):
    number: Incomplete
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

@disjoint_base
class Constraint:
    data: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def getConshdlrName(self) -> Incomplete: ...
    def isActive(self) -> Incomplete: ...
    def isChecked(self) -> Incomplete: ...
    def isDynamic(self) -> Incomplete: ...
    def isEnforced(self) -> Incomplete: ...
    def isInitial(self) -> Incomplete: ...
    def isKnapsack(self) -> Incomplete: ...
    def isLinear(self) -> Incomplete: ...
    def isLinearType(self) -> Incomplete: ...
    def isLocal(self) -> Incomplete: ...
    def isModifiable(self) -> Incomplete: ...
    def isNonlinear(self) -> Incomplete: ...
    def isOriginal(self) -> Incomplete: ...
    def isPropagated(self) -> Incomplete: ...
    def isRemovable(self) -> Incomplete: ...
    def isSeparated(self) -> Incomplete: ...
    def isStickingAtNode(self) -> Incomplete: ...
    def ptr(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class Cutsel:
    model: Incomplete
    def __init__(self) -> None: ...
    def cutselexit(self) -> Incomplete: ...
    def cutselexitsol(self) -> Incomplete: ...
    def cutselfree(self) -> Incomplete: ...
    def cutselinit(self) -> Incomplete: ...
    def cutselinitsol(self) -> Incomplete: ...
    def cutselselect(
        self,
        cuts: Incomplete,
        forcedcuts: Incomplete,
        root: Incomplete,
        maxnselectedcuts: Incomplete,
    ) -> Incomplete: ...

@disjoint_base
class DomainChanges:
    def __init__(self) -> None: ...
    def getBoundchgs(self) -> Incomplete: ...

@disjoint_base
class Event:
    data: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def _getEventNames(self) -> Incomplete: ...
    def getName(self) -> Incomplete: ...
    def getNewBound(self) -> Incomplete: ...
    def getNode(self) -> Incomplete: ...
    def getOldBound(self) -> Incomplete: ...
    def getRow(self) -> Incomplete: ...
    def getType(self) -> Incomplete: ...
    def getVar(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class Eventhdlr:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def eventcopy(self) -> Incomplete: ...
    def eventdelete(self) -> Incomplete: ...
    def eventexec(self, event: Incomplete) -> Incomplete: ...
    def eventexit(self) -> Incomplete: ...
    def eventexitsol(self) -> Incomplete: ...
    def eventfree(self) -> Incomplete: ...
    def eventinit(self) -> Incomplete: ...
    def eventinitsol(self) -> Incomplete: ...

class ExprLike:
    def __array_ufunc__(
        self,
        ufunc: np.ufunc,
        method: str,
        *args: Incomplete,
        **kwargs: Incomplete,
    ) -> Incomplete: ...
    def __abs__(self) -> GenExpr: ...
    def exp(self) -> GenExpr: ...
    def log(self) -> GenExpr: ...
    def sqrt(self) -> GenExpr: ...
    def sin(self) -> GenExpr: ...
    def cos(self) -> GenExpr: ...

@disjoint_base
class Expr(ExprLike):
    terms: Incomplete
    def __init__(self, terms: Incomplete = ...) -> None: ...
    def degree(self) -> Incomplete: ...
    def normalize(self) -> Incomplete: ...
    def __abs__(self) -> GenExpr: ...
    def __add__(self, other: Incomplete, /) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __getitem__(self, index: Incomplete, /) -> Incomplete: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __iadd__(self, other: Incomplete, /) -> Incomplete: ...  # noqa: PYI034
    def __iter__(self) -> Incomplete: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __mul__(self, other: Incomplete, /) -> Incomplete: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __neg__(self) -> Incomplete: ...
    def __pow__(self, other: Incomplete, modulo: Incomplete = ..., /) -> Incomplete: ...
    def __radd__(self, other: Incomplete, /) -> Incomplete: ...
    def __rmul__(self, other: Incomplete, /) -> Incomplete: ...
    def __rpow__(self, other: Incomplete, /) -> Incomplete: ...
    def __rsub__(self, other: Incomplete, /) -> Incomplete: ...
    def __rtruediv__(self, other: Incomplete, /) -> Incomplete: ...
    def __sub__(self, other: Incomplete, /) -> Incomplete: ...
    def __truediv__(self, other: Incomplete, /) -> Incomplete: ...

@disjoint_base
class ExprCons:
    _lhs: Incomplete
    _rhs: Incomplete
    expr: Incomplete
    def __init__(
        self, expr: Incomplete, lhs: Incomplete = ..., rhs: Incomplete = ...
    ) -> None: ...
    def normalize(self) -> Incomplete: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class GenExpr(ExprLike):
    _op: Incomplete
    children: Incomplete
    def __init__(self) -> None: ...
    def degree(self) -> Incomplete: ...
    def getOp(self) -> Incomplete: ...
    def __abs__(self) -> GenExpr: ...
    def __add__(self, other: Incomplete, /) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __mul__(self, other: Incomplete, /) -> Incomplete: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __neg__(self) -> Incomplete: ...
    def __pow__(self, other: Incomplete, modulo: Incomplete = ..., /) -> Incomplete: ...
    def __radd__(self, other: Incomplete, /) -> Incomplete: ...
    def __rmul__(self, other: Incomplete, /) -> Incomplete: ...
    def __rpow__(self, other: Incomplete, /) -> Incomplete: ...
    def __rsub__(self, other: Incomplete, /) -> Incomplete: ...
    def __rtruediv__(self, other: Incomplete, /) -> Incomplete: ...
    def __sub__(self, other: Incomplete, /) -> Incomplete: ...
    def __truediv__(self, other: Incomplete, /) -> Incomplete: ...

@disjoint_base
class Heur:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def heurexec(
        self, heurtiming: Incomplete, nodeinfeasible: Incomplete
    ) -> Incomplete: ...
    def heurexit(self) -> Incomplete: ...
    def heurexitsol(self) -> Incomplete: ...
    def heurfree(self) -> Incomplete: ...
    def heurinit(self) -> Incomplete: ...
    def heurinitsol(self) -> Incomplete: ...

@disjoint_base
class IIS:
    def __init__(self) -> None: ...
    def getNNodes(self) -> Incomplete: ...
    def getSubscip(self) -> Incomplete: ...
    def getTime(self) -> Incomplete: ...
    def greedyMakeIrreducible(self) -> Incomplete: ...
    def isSubscipInfeasible(self) -> Incomplete: ...
    def isSubscipIrreducible(self) -> Incomplete: ...
    def setSubscipInfeasible(self, infeasible: Incomplete) -> Incomplete: ...
    def setSubscipIrreducible(self, irreducible: Incomplete) -> Incomplete: ...

@disjoint_base
class IISfinder:
    model: Incomplete
    iis: Incomplete
    def __init__(self) -> None: ...
    def iisfinderexec(self) -> Incomplete: ...
    def iisfinderfree(self) -> Incomplete: ...

@disjoint_base
class LP:
    name: Incomplete
    def __init__(self, name: Incomplete = ..., sense: Incomplete = ...) -> None: ...
    def addCol(
        self,
        entries: Incomplete,
        obj: Incomplete = ...,
        lb: Incomplete = ...,
        ub: Incomplete = ...,
    ) -> Incomplete: ...
    def addCols(
        self,
        entrieslist: Incomplete,
        objs: Incomplete = ...,
        lbs: Incomplete = ...,
        ubs: Incomplete = ...,
    ) -> Incomplete: ...
    def addRow(
        self, entries: Incomplete, lhs: Incomplete = ..., rhs: Incomplete = ...
    ) -> Incomplete: ...
    def addRows(
        self, entrieslist: Incomplete, lhss: Incomplete = ..., rhss: Incomplete = ...
    ) -> Incomplete: ...
    def chgBound(
        self, col: Incomplete, lb: Incomplete, ub: Incomplete
    ) -> Incomplete: ...
    def chgCoef(
        self, row: Incomplete, col: Incomplete, newval: Incomplete
    ) -> Incomplete: ...
    def chgObj(self, col: Incomplete, obj: Incomplete) -> Incomplete: ...
    def chgSide(
        self, row: Incomplete, lhs: Incomplete, rhs: Incomplete
    ) -> Incomplete: ...
    def clear(self) -> Incomplete: ...
    def delCols(self, firstcol: Incomplete, lastcol: Incomplete) -> Incomplete: ...
    def delRows(self, firstrow: Incomplete, lastrow: Incomplete) -> Incomplete: ...
    def getActivity(self) -> Incomplete: ...
    def getBase(self) -> Incomplete: ...
    def getBasisInds(self) -> Incomplete: ...
    def getBounds(
        self, firstcol: Incomplete = ..., lastcol: Incomplete = ...
    ) -> Incomplete: ...
    def getDual(self) -> Incomplete: ...
    def getDualRay(self) -> Incomplete: ...
    def getIntParam(self, param: Incomplete) -> Incomplete: ...
    def getNIterations(self) -> Incomplete: ...
    def getObjVal(self) -> Incomplete: ...
    def getPrimal(self) -> Incomplete: ...
    def getPrimalRay(self) -> Incomplete: ...
    def getRealParam(self, param: Incomplete) -> Incomplete: ...
    def getRedcost(self) -> Incomplete: ...
    def getSides(
        self, firstrow: Incomplete = ..., lastrow: Incomplete = ...
    ) -> Incomplete: ...
    def infinity(self) -> Incomplete: ...
    def isDualFeasible(self) -> Incomplete: ...
    def isInfinity(self, val: Incomplete) -> Incomplete: ...
    def isOptimal(self) -> Incomplete: ...
    def isPrimalFeasible(self) -> Incomplete: ...
    def ncols(self) -> Incomplete: ...
    def nrows(self) -> Incomplete: ...
    def readLP(self, filename: Incomplete) -> Incomplete: ...
    def setBase(self, cstat: Incomplete, rstat: Incomplete) -> Incomplete: ...
    def setIntParam(self, param: Incomplete, value: Incomplete) -> Incomplete: ...
    def setRealParam(self, param: Incomplete, value: Incomplete) -> Incomplete: ...
    def solve(self, dual: Incomplete = ...) -> Incomplete: ...
    def writeLP(self, filename: Incomplete) -> Incomplete: ...

class MatrixConstraint(np.ndarray):
    def getConshdlrName(self) -> Incomplete: ...
    def isActive(self) -> Incomplete: ...
    def isChecked(self) -> Incomplete: ...
    def isDynamic(self) -> Incomplete: ...
    def isEnforced(self) -> Incomplete: ...
    def isInitial(self) -> Incomplete: ...
    def isLinear(self) -> Incomplete: ...
    def isLocal(self) -> Incomplete: ...
    def isModifiable(self) -> Incomplete: ...
    def isNonlinear(self) -> Incomplete: ...
    def isPropagated(self) -> Incomplete: ...
    def isRemovable(self) -> Incomplete: ...
    def isSeparated(self) -> Incomplete: ...
    def isStickingAtNode(self) -> Incomplete: ...

class MatrixExpr(np.ndarray):
    def _evaluate(self, sol: Incomplete) -> Incomplete: ...
    def __array_ufunc__(
        self,
        ufunc: np.ufunc,
        method: str,
        *args: Incomplete,
        **kwargs: Incomplete,
    ) -> Incomplete: ...

class MatrixExprCons(np.ndarray):
    def __array_ufunc__(
        self,
        ufunc: np.ufunc,
        method: str,
        *args: Incomplete,
        **kwargs: Incomplete,
    ) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...

class MatrixGenExpr(MatrixExpr): ...

class MatrixVariable(MatrixExpr):
    def getAvgSol(self) -> Incomplete: ...
    def getCol(self) -> Incomplete: ...
    def getIndex(self) -> Incomplete: ...
    def getLPSol(self) -> Incomplete: ...
    def getLbGlobal(self) -> Incomplete: ...
    def getLbLocal(self) -> Incomplete: ...
    def getLbOriginal(self) -> Incomplete: ...
    def getObj(self) -> Incomplete: ...
    def getUbGlobal(self) -> Incomplete: ...
    def getUbLocal(self) -> Incomplete: ...
    def getUbOriginal(self) -> Incomplete: ...
    def isInLP(self) -> Incomplete: ...
    def varMayRound(self, direction: Incomplete = ...) -> Incomplete: ...
    def vtype(self) -> Incomplete: ...

@disjoint_base
class Model:
    _freescip: Incomplete
    data: Incomplete
    def __init__(
        self,
        problemName: str = "model",
        defaultPlugins: bool = True,
        sourceModel: Model | None = None,
        origcopy: bool = False,
        globalcopy: bool = True,
        enablepricing: bool = True,
        createscip: bool = True,
        threadsafe: bool = False,
    ) -> None: ...
    def _createConsGenNonlinear(self, cons: Incomplete) -> Incomplete: ...
    def _createConsLinear(self, lincons: Incomplete) -> Incomplete: ...
    def _createConsNonlinear(self, cons: Incomplete) -> Incomplete: ...
    def _createConsQuadratic(self, quadcons: Incomplete) -> Incomplete: ...
    def _getStageNames(self) -> Incomplete: ...
    def activateBenders(self, benders: Benders, nsubproblems: int) -> None: ...
    def addBendersSubproblem(self, benders: Benders, subproblem: Model) -> None: ...
    def addCoefKnapsack(
        self, cons: Constraint, var: Variable, weight: float
    ) -> None: ...
    def addCoefLinear(self, cons: Constraint, var: Variable, value: float) -> None: ...
    def addCons(
        self,
        cons: Incomplete,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsAnd(
        self,
        vars: Sequence[Variable],
        resvar: Variable,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsCardinality(
        self,
        consvars: Sequence[Variable],
        cardval: int,
        indvars: Sequence[Variable] | None = None,
        weights: Sequence[float] | None = None,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsCoeff(self, cons: Constraint, var: Variable, coeff: float) -> None: ...
    def addConsDisjunction(
        self,
        conss: Iterable[Incomplete],
        name: str = "",
        initial: bool = True,
        relaxcons: Constraint | None = None,
        enforce: bool = True,
        check: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
    ) -> Constraint: ...
    def addConsElemDisjunction(
        self, disj_cons: Constraint, cons: Constraint
    ) -> Constraint: ...
    def addConsIndicator(
        self,
        cons: Incomplete,
        binvar: Variable | None = None,
        activeone: bool = True,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsKnapsack(
        self,
        vars: Sequence[Variable],
        weights: Sequence[int],
        capacity: int,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        modifiable: bool = False,
        propagate: bool = True,
        local: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsLocal(
        self,
        cons: Incomplete,
        validnode: Node | None = None,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = True,
        dynamic: bool = False,
        removable: bool = True,
        stickingatnode: bool = True,
    ) -> Constraint: ...
    def addConsNode(
        self,
        node: Node,
        cons: Incomplete,
        validnode: Node | None = None,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = True,
        dynamic: bool = False,
        removable: bool = True,
        stickingatnode: bool = True,
    ) -> Constraint: ...
    def addConsOr(
        self,
        vars: Sequence[Variable],
        resvar: Variable,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsSOS1(
        self,
        vars: Sequence[Variable],
        weights: Sequence[float] | None = None,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsSOS2(
        self,
        vars: Sequence[Variable],
        weights: Sequence[float] | None = None,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConsXor(
        self,
        vars: Sequence[Variable],
        rhsvar: bool,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def addConss(
        self,
        conss: Iterable[Incomplete],
        name: str | Iterable[str] = "",
        initial: bool | Iterable[bool] = True,
        separate: bool | Iterable[bool] = True,
        enforce: bool | Iterable[bool] = True,
        check: bool | Iterable[bool] = True,
        propagate: bool | Iterable[bool] = True,
        local: bool | Iterable[bool] = False,
        modifiable: bool | Iterable[bool] = False,
        dynamic: bool | Iterable[bool] = False,
        removable: bool | Iterable[bool] = False,
        stickingatnode: bool | Iterable[bool] = False,
    ) -> list[Constraint]: ...
    def addCut(self, cut: Row, forcecut: bool = False) -> bool: ...
    def addExprNonlinear(
        self, cons: Constraint, expr: Incomplete, coef: float
    ) -> None: ...
    def addMatrixCons(
        self,
        cons: Incomplete,
        name: str | np.ndarray = "",
        initial: bool | np.ndarray = True,
        separate: bool | np.ndarray = True,
        enforce: bool | np.ndarray = True,
        check: bool | np.ndarray = True,
        propagate: bool | np.ndarray = True,
        local: bool | np.ndarray = False,
        modifiable: bool | np.ndarray = False,
        dynamic: bool | np.ndarray = False,
        removable: bool | np.ndarray = False,
        stickingatnode: bool | np.ndarray = False,
    ) -> MatrixConstraint: ...
    def addMatrixConsDisjunction(
        self,
        conss: Incomplete,
        name: str | np.ndarray = "",
        initial: bool | np.ndarray = True,
        relaxcons: None = None,
        enforce: bool | np.ndarray = True,
        check: bool | np.ndarray = True,
        local: bool | np.ndarray = False,
        modifiable: bool | np.ndarray = False,
        dynamic: bool | np.ndarray = False,
    ) -> Incomplete: ...
    def addMatrixConsIndicator(
        self,
        cons: Incomplete,
        binvar: Variable | MatrixVariable | None = None,
        activeone: bool | np.ndarray = True,
        name: str | np.ndarray = "",
        initial: bool | np.ndarray = True,
        separate: bool | np.ndarray = True,
        enforce: bool | np.ndarray = True,
        check: bool | np.ndarray = True,
        propagate: bool | np.ndarray = True,
        local: bool | np.ndarray = False,
        dynamic: bool | np.ndarray = False,
        removable: bool | np.ndarray = False,
        stickingatnode: bool | np.ndarray = False,
    ) -> MatrixConstraint: ...
    def addMatrixVar(
        self,
        shape: int | tuple[int, ...],
        name: str | np.ndarray = "",
        vtype: str | np.ndarray = "C",
        lb: float | np.ndarray | None = 0.0,
        ub: float | np.ndarray | None = None,
        obj: float | np.ndarray | None = 0.0,
        pricedVar: bool | np.ndarray = False,
        pricedVarScore: float | np.ndarray | None = 1.0,
    ) -> MatrixVariable: ...
    def addObjoffset(self, offset: float, solutions: bool = False) -> None: ...
    def addPoolCut(self, row: Row) -> None: ...
    def addPyCons(self, cons: Constraint) -> None: ...
    def addRowDive(self, row: Row) -> None: ...
    def addRowExact(self, rowexact: RowExact) -> None: ...
    def addSol(self, solution: Solution, free: bool = True) -> bool: ...
    def addVar(
        self,
        name: str = "",
        vtype: str = "C",
        lb: float | None = 0.0,
        ub: float | None = None,
        obj: float | None = 0.0,
        pricedVar: bool = False,
        pricedVarScore: float = 1.0,
        deletable: bool = False,
    ) -> Variable: ...
    def addVarLocks(self, var: Variable, nlocksdown: int, nlocksup: int) -> None: ...
    def addVarLocksType(
        self, var: Variable, locktype: int, nlocksdown: int, nlocksup: int
    ) -> None: ...
    def addVarSOS1(self, cons: Constraint, var: Variable, weight: float) -> None: ...
    def addVarSOS2(self, cons: Constraint, var: Variable, weight: float) -> None: ...
    def addVarToRow(self, row: Row, var: Variable, value: float) -> None: ...
    def adjustedVarLb(self, var: Variable, lb: float) -> float: ...
    def adjustedVarUb(self, var: Variable, ub: float) -> float: ...
    def aggregateVars(
        self,
        varx: Variable,
        vary: Variable,
        coefx: float = 1.0,
        coefy: float = -1.0,
        rhs: float = 0.0,
    ) -> tuple[bool, bool, bool]: ...
    def allColsInLP(self) -> bool: ...
    def allowNegSlackExact(self) -> bool: ...
    def appendVarSOS1(self, cons: Constraint, var: Variable) -> None: ...
    def appendVarSOS2(self, cons: Constraint, var: Variable) -> None: ...
    def applyCutsProbing(self) -> bool: ...
    def attachEventHandlerCallback(
        self,
        callback: Incomplete,
        events: Incomplete,
        name: Incomplete = ...,
        description: Incomplete = ...,
    ) -> Incomplete: ...
    def backtrackProbing(self, probingdepth: int) -> None: ...
    def branchLPExact(self) -> Incomplete: ...
    def branchVar(self, variable: Variable) -> tuple[Node, Node | None, Node]: ...
    def branchVarVal(
        self, variable: Variable, value: float
    ) -> tuple[Node, Node | None, Node]: ...
    def cacheRowExtensions(self, row: Row) -> None: ...
    def calcChildEstimate(self, variable: Variable, targetvalue: float) -> float: ...
    def calcNodeselPriority(
        self, variable: Variable, branchdir: Incomplete, targetvalue: float
    ) -> float: ...
    def catchEvent(self, eventtype: Incomplete, eventhdlr: Eventhdlr) -> None: ...
    def catchRowEvent(
        self, row: Row, eventtype: Incomplete, eventhdlr: Eventhdlr
    ) -> None: ...
    def catchVarEvent(
        self, var: Variable, eventtype: Incomplete, eventhdlr: Eventhdlr
    ) -> None: ...
    def checkBendersSubproblemOptimality(
        self, solution: Solution, probnumber: int, benders: Benders | None = None
    ) -> bool: ...
    def checkQuadraticNonlinear(self, cons: Constraint) -> bool: ...
    def checkSol(
        self,
        solution: Solution,
        printreason: bool = True,
        completely: bool = False,
        checkbounds: bool = True,
        checkintegrality: bool = True,
        checklprows: bool = True,
        original: bool = False,
    ) -> bool: ...
    def chgCapacityKnapsack(self, cons: Constraint, capacity: float | None) -> None: ...
    def chgCoefLinear(self, cons: Constraint, var: Variable, value: float) -> None: ...
    def chgLhs(self, cons: Constraint, lhs: float | None) -> None: ...
    def chgReoptObjective(
        self, coeffs: Expr, sense: Literal["minimize", "maximize"] = "minimize"
    ) -> None: ...
    def chgRhs(self, cons: Constraint, rhs: float | None) -> None: ...
    def chgRowLhsDive(self, row: Row, newlhs: float) -> None: ...
    def chgRowRhsDive(self, row: Row, newrhs: float) -> None: ...
    def chgVarBranchPriority(self, var: Variable, priority: int) -> None: ...
    def chgVarLb(self, var: Variable, lb: float | None) -> None: ...
    def chgVarLbDive(self, var: Variable, newbound: float) -> None: ...
    def chgVarLbGlobal(self, var: Variable, lb: float | None) -> None: ...
    def chgVarLbNode(self, node: Node, var: Variable, lb: float | None) -> None: ...
    def chgVarLbProbing(self, var: Variable, lb: float | None) -> None: ...
    def chgVarObjDive(self, var: Variable, newobj: float) -> None: ...
    def chgVarObjProbing(self, var: Variable, newobj: float) -> None: ...
    def chgVarType(self, var: Variable, vtype: str) -> None: ...
    def chgVarUb(self, var: Variable, ub: float | None) -> None: ...
    def chgVarUbDive(self, var: Variable, newbound: float) -> None: ...
    def chgVarUbGlobal(self, var: Variable, ub: float | None) -> None: ...
    def chgVarUbNode(self, node: Node, var: Variable, ub: float | None) -> None: ...
    def chgVarUbProbing(self, var: Variable, ub: float | None) -> None: ...
    def computeBestSolSubproblems(self) -> None: ...
    def constructLP(self) -> bool: ...
    def copyLargeNeighborhoodSearch(
        self, to_fix: Sequence[Variable], fix_vals: Sequence[float]
    ) -> Model: ...
    def count(self) -> None: ...
    def createChild(self, nodeselprio: float, estimate: float) -> Node: ...
    def createCons(
        self,
        conshdlr: Conshdlr,
        name: str,
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def createConsFromExpr(
        self,
        cons: Incomplete,
        name: str = "",
        initial: bool = True,
        separate: bool = True,
        enforce: bool = True,
        check: bool = True,
        propagate: bool = True,
        local: bool = False,
        modifiable: bool = False,
        dynamic: bool = False,
        removable: bool = False,
        stickingatnode: bool = False,
    ) -> Constraint: ...
    def createEmptyRowSepa(
        self,
        sepa: Sepa,
        name: str = "row",
        lhs: float | None = 0.0,
        rhs: float | None = None,
        local: bool = True,
        modifiable: bool = False,
        removable: bool = True,
    ) -> Row: ...
    def createEmptyRowUnspec(
        self,
        name: str = "row",
        lhs: float | None = 0.0,
        rhs: float | None = None,
        local: bool = True,
        modifiable: bool = False,
        removable: bool = True,
    ) -> Row: ...
    def createOrigSol(self, heur: Heur | None = None) -> Solution: ...
    def createPartialSol(self, heur: Heur | None = None) -> Solution: ...
    def createProbBasic(self, problemName: str = "model") -> None: ...
    def createSol(self, heur: Heur | None = None, initlp: bool = False) -> Solution: ...
    def cutoffNode(self, node: Node) -> None: ...
    def deactivatePricer(self, pricer: Pricer) -> None: ...
    def delCoefLinear(self, cons: Constraint, var: Variable) -> None: ...
    def delCons(self, cons: Constraint) -> None: ...
    def delConsLocal(self, cons: Constraint) -> None: ...
    def delVar(self, var: Variable) -> bool: ...
    def disableDebugSol(self) -> None: ...
    def disablePropagation(self, onlyroot: bool = False) -> None: ...
    def dropEvent(self, eventtype: Incomplete, eventhdlr: Eventhdlr) -> None: ...
    def dropRowEvent(
        self, row: Row, eventtype: Incomplete, eventhdlr: Eventhdlr
    ) -> None: ...
    def dropVarEvent(
        self, var: Variable, eventtype: Incomplete, eventhdlr: Eventhdlr
    ) -> None: ...
    def enableDebugSol(self) -> None: ...
    def enableExactSolving(self, enable: bool) -> None: ...
    def enableReoptimization(self, enable: bool = True) -> None: ...
    def endDive(self) -> None: ...
    def endProbing(self) -> None: ...
    def endStrongbranch(self) -> None: ...
    def epsilon(self) -> float: ...
    def feasCeil(self, value: float) -> float: ...
    def feasFloor(self, value: float) -> float: ...
    def feasFrac(self, value: float) -> float: ...
    def feasRound(self, value: float) -> float: ...
    def feastol(self) -> float: ...
    def fixVar(self, var: Variable, val: float) -> tuple[bool, bool]: ...
    def fixVarProbing(self, var: Variable, fixedval: float) -> None: ...
    def flushRowExtensions(self, row: Row) -> None: ...
    def frac(self, value: float) -> float: ...
    def free(self) -> None: ...
    def freeBendersSubproblems(self) -> None: ...
    def freeProb(self) -> None: ...
    def freeReoptSolve(self) -> None: ...
    def freeSol(self, solution: Solution) -> None: ...
    def freeTransform(self) -> None: ...
    @staticmethod
    def from_ptr(capsule: CapsuleType, take_ownership: bool) -> Model: ...
    def generateIIS(self) -> IIS: ...
    def getActivity(self, cons: Constraint, sol: Solution | None = None) -> float: ...
    def getBendersAuxiliaryVar(
        self, probnumber: int, benders: Benders | None = None
    ) -> Variable: ...
    def getBendersSubproblem(
        self, probnumber: int, benders: Benders | None = None
    ) -> Model: ...
    def getBendersVar(
        self, var: Variable, benders: Benders | None = None, probnumber: int = -1
    ) -> Variable | None: ...
    def getBestChild(self) -> Node | None: ...
    def getBestLeaf(self) -> Node | None: ...
    def getBestNode(self) -> Node | None: ...
    def getBestSibling(self) -> Node | None: ...
    def getBestSol(self) -> Solution | None: ...
    def getBestboundNode(self) -> Node | None: ...
    def getBipartiteGraphRepresentation(
        self,
        prev_col_features: Sequence[Sequence[float]] | None = None,
        prev_edge_features: Sequence[Sequence[float]] | None = None,
        prev_row_features: Sequence[Sequence[float]] | None = None,
        static_only: bool = False,
        suppress_warnings: bool = False,
    ) -> tuple[
        list[list[float | None]],
        list[list[float]],
        list[list[float]],
        dict[str, dict[str, int]],
    ]: ...
    def getBranchScoreMultiple(self, var: Variable, gains: list[float]) -> float: ...
    def getCapacityKnapsack(self, cons: Constraint) -> float: ...
    def getChildren(self) -> list[Node]: ...
    def getColRedCost(self, col: Column) -> float: ...
    def getCondition(self, exact: bool = False) -> float: ...
    def getConsNVars(self, constraint: Constraint) -> int: ...
    def getConsVals(self, constraint: Constraint) -> list[float]: ...
    def getConsVars(self, constraint: Constraint) -> list[Variable]: ...
    def getConss(self, transformed: bool = True) -> list[Constraint]: ...
    def getCurrentNode(self) -> Node: ...
    def getCutEfficacy(self, cut: Row, sol: Solution | None = None) -> float: ...
    def getCutLPSolCutoffDistance(self, cut: Row, sol: Solution) -> float: ...
    def getCutoffbound(self) -> float: ...
    def getDepth(self) -> int: ...
    def getDualMultiplier(self, cons: Constraint) -> float: ...
    def getDualSolVal(
        self, cons: Constraint, boundconstraint: bool = False
    ) -> float: ...
    def getDualbound(self) -> float: ...
    def getDualboundRoot(self) -> float: ...
    def getDualfarkasKnapsack(self, cons: Constraint) -> float: ...
    def getDualfarkasLinear(self, cons: Constraint) -> float: ...
    def getDualsolKnapsack(self, cons: Constraint) -> float: ...
    def getDualsolLinear(self, cons: Constraint) -> float: ...
    def getGap(self) -> float: ...
    def getHeurTiming(self, heurname: str) -> Incomplete: ...
    def getIIS(self) -> IIS: ...
    def getLPBInvARow(self, row: int) -> list[float]: ...
    def getLPBInvRow(self, row: int) -> list[float]: ...
    def getLPBasisInd(self) -> list[int]: ...
    def getLPBranchCands(
        self,
    ) -> tuple[list[Variable], list[float], list[float], int, int, int]: ...
    def getLPColsData(self) -> list[Column]: ...
    def getLPObjVal(self) -> float: ...
    def getLPRowsData(self) -> list[Row]: ...
    def getLPSolstat(self) -> Incomplete: ...
    def getLeaves(self) -> list[Node]: ...
    def getLhs(self, cons: Constraint) -> float: ...
    def getLinearConsIndicator(self, cons: Constraint) -> Constraint | None: ...
    def getLocalEstimate(self, original: bool = False) -> float: ...
    def getLowerbound(self) -> float: ...
    def getMajorVersion(self) -> int: ...
    def getMaxDepth(self) -> int: ...
    def getMinorVersion(self) -> int: ...
    def getNBestSolsFound(self) -> int: ...
    def getNBinVars(self) -> int: ...
    def getNChildren(self) -> int: ...
    def getNConss(self, transformed: bool = True) -> int: ...
    def getNContVars(self) -> int: ...
    def getNCountedSols(self) -> int: ...
    def getNCuts(self) -> int: ...
    def getNCutsApplied(self) -> int: ...
    def getNFeasibleLeaves(self) -> int: ...
    def getNImplVars(self) -> int: ...
    def getNInfeasibleLeaves(self) -> int: ...
    def getNIntVars(self) -> int: ...
    def getNLPBranchCands(self) -> int: ...
    def getNLPCols(self) -> int: ...
    def getNLPIterations(self) -> int: ...
    def getNLPRows(self) -> int: ...
    def getNLPs(self) -> int: ...
    def getMemUsed(self) -> int: ...
    def getMemTotal(self) -> int: ...
    def getMemExternEstim(self) -> int: ...
    def getNLeaves(self) -> int: ...
    def getNLimSolsFound(self) -> int: ...
    def getNNlRows(self) -> int: ...
    def getNNodeLPIterations(self) -> int: ...
    def getNNodes(self) -> int: ...
    def getNReaders(self) -> int: ...
    def getNSepaRounds(self) -> int: ...
    def getNSiblings(self) -> int: ...
    def getNSols(self) -> int: ...
    def getNSolsFound(self) -> int: ...
    def getNStrongbranchLPIterations(self) -> int: ...
    def getPrimalDualIntegral(self) -> Incomplete: ...
    def getNTotalNodes(self) -> int: ...
    def getNVars(self, transformed: bool = True) -> int: ...
    def getNVarsAnd(self, and_cons: Constraint) -> int: ...
    def getNlRowActivityBounds(self, nlrow: NLRow) -> tuple[float, float]: ...
    def getNlRowSolActivity(
        self, nlrow: NLRow, sol: Solution | None = None
    ) -> float: ...
    def getNlRowSolFeasibility(
        self, nlrow: NLRow, sol: Solution | None = None
    ) -> float: ...
    def getNlRows(self) -> list[NLRow]: ...
    def getObjVal(self, original: bool = True) -> float: ...
    def getObjective(self) -> Expr: ...
    def getObjectiveSense(self) -> Literal["maximize", "minimize", "unknown"]: ...
    def getObjlimit(self) -> float: ...
    def getObjoffset(self, original: bool = True) -> float: ...
    def getOpenNodes(self) -> tuple[list[Node], list[Node], list[Node]]: ...
    def getParam(self, name: str) -> bool | float | str: ...
    def getParams(self) -> dict[str, bool | float | str]: ...
    def getPlungeDepth(self) -> int: ...
    def getPresolvingTime(self) -> float: ...
    def getPrimalRay(self) -> list[float]: ...
    def getPrimalRayVal(self, var: Variable) -> float: ...
    def getPrimalbound(self) -> float: ...
    def getPrioChild(self) -> Node | None: ...
    def getPrioSibling(self) -> Node | None: ...
    def getProbName(self) -> str: ...
    def getProbingDepth(self) -> int: ...
    def getPseudoBranchCands(self) -> tuple[list[Variable], int, int]: ...
    def getReadingTime(self) -> float: ...
    def getResultantAnd(self, and_cons: Constraint) -> Variable: ...
    def getRhs(self, cons: Constraint) -> float: ...
    def getRowActivity(self, row: Row) -> float: ...
    def getRowDualSol(self, row: Row) -> float: ...
    def getRowLPActivity(self, row: Row) -> float: ...
    def getRowLinear(self, cons: Constraint) -> Row: ...
    def getRowNumIntCols(self, row: Row) -> int: ...
    def getRowObjParallelism(self, row: Row) -> float: ...
    def getRowParallelism(
        self, row1: Row, row2: Row, orthofunc: Literal["d", "e", 100, 101] = 101
    ) -> float: ...
    def getSiblings(self) -> list[Node]: ...
    def getSlack(
        self,
        cons: Constraint,
        sol: Solution | None = None,
        side: Literal["lhs", "rhs"] | None = None,
    ) -> float: ...
    def getSlackVarIndicator(self, cons: Constraint) -> Variable: ...
    def getSolObjVal(self, sol: Solution | None, original: bool = True) -> float: ...
    def getSolTime(self, sol: Solution) -> float: ...
    @overload
    def getSolVal(self, sol: Solution, expr: Union[Expr, GenExpr]) -> float: ...
    @overload
    def getSolVal(self, sol: Solution, expr: MatrixExpr) -> np.ndarray: ...
    def getSols(self) -> list[Solution]: ...
    def getSolvingTime(self) -> float: ...
    def getStage(self) -> Incomplete: ...
    def getStageName(self) -> str: ...
    def getStatus(
        self,
    ) -> Literal[
        "optimal",
        "timelimit",
        "infeasible",
        "unbounded",
        "userinterrupt",
        "inforunbd",
        "nodelimit",
        "totalnodelimit",
        "stallnodelimit",
        "gaplimit",
        "memlimit",
        "sollimit",
        "bestsollimit",
        "restartlimit",
        "primallimit",
        "duallimit",
        "unknown",
    ]: ...
    def getTechVersion(self) -> int: ...
    def getTermsQuadratic(
        self, cons: Constraint
    ) -> tuple[
        list[tuple[Variable, Variable, float]],
        list[tuple[Variable, float, float]],
        list[tuple[Variable, float]],
    ]: ...
    def getTotalTime(self) -> float: ...
    def getTransformedCons(self, cons: Constraint) -> Constraint: ...
    def getTransformedVar(self, var: Variable) -> Variable: ...
    def getTreesizeEstimation(self) -> float: ...
    @overload
    def getVal(self, expr: Union[Expr, GenExpr]) -> float: ...
    @overload
    def getVal(self, expr: MatrixExpr) -> np.ndarray: ...
    def getValsLinear(self, cons: Constraint) -> dict[str, float]: ...
    def getVarDict(self, transformed: bool = False) -> dict[str, float]: ...
    def getVarLbDive(self, var: Variable) -> float: ...
    def getVarPseudocost(self, var: Variable, branchdir: Incomplete) -> float: ...
    def getVarPseudocostScore(self, var: Variable, solVal: float) -> float: ...
    def getVarRedcost(self, var: Variable) -> float: ...
    def getVarStrongbranch(
        self,
        var: Variable,
        itlim: int,
        idempotent: bool = False,
        integral: bool = False,
    ) -> tuple[float, float, bool, bool, bool, bool, bool, bool, bool]: ...
    def getVarStrongbranchLast(
        self, var: Variable
    ) -> tuple[float, float, bool, bool, float, float]: ...
    def getVarStrongbranchNode(self, var: Variable) -> int: ...
    def getVarUbDive(self, var: Variable) -> float: ...
    def getVars(self, transformed: bool = False) -> list[Variable]: ...
    def getVarsAnd(self, and_cons: Constraint) -> list[Variable]: ...
    def getWeightsKnapsack(self, cons: Constraint) -> dict[str, float]: ...
    def hasPrimalRay(self) -> bool: ...
    def hideOutput(self, quiet: bool = True) -> None: ...
    def inProbing(self) -> bool: ...
    def inRepropagation(self) -> bool: ...
    def includeBenders(
        self,
        benders: Benders,
        name: str,
        desc: str,
        priority: int = 1,
        cutlp: bool = True,
        cutpseudo: bool = True,
        cutrelax: bool = True,
        shareaux: bool = False,
    ) -> None: ...
    def includeBendersDefaultCuts(self, benders: Benders) -> None: ...
    def includeBenderscut(
        self,
        benders: Benders,
        benderscut: Benderscut,
        name: str,
        desc: str,
        priority: int = 1,
        islpcut: bool = True,
    ) -> None: ...
    def includeBranchrule(
        self,
        branchrule: Branchrule,
        name: str,
        desc: str,
        priority: int,
        maxdepth: int,
        maxbounddist: float,
    ) -> None: ...
    def includeConshdlr(
        self,
        conshdlr: Conshdlr,
        name: str,
        desc: str,
        sepapriority: int = 0,
        enfopriority: int = 0,
        chckpriority: int = 0,
        sepafreq: int = -1,
        propfreq: int = -1,
        eagerfreq: int = 100,
        maxprerounds: int = -1,
        delaysepa: bool = False,
        delayprop: bool = False,
        needscons: bool = True,
        proptiming: Incomplete = ...,
        presoltiming: Incomplete = ...,
    ) -> None: ...
    def includeCutsel(
        self, cutsel: Cutsel, name: str, desc: str, priority: int
    ) -> None: ...
    def includeDefaultPlugins(self) -> None: ...
    def includeEventhdlr(self, eventhdlr: Eventhdlr, name: str, desc: str) -> None: ...
    def includeHeur(
        self,
        heur: Heur,
        name: str,
        desc: str,
        dispchar: str,
        priority: int = 10000,
        freq: int = 1,
        freqofs: int = 0,
        maxdepth: int = -1,
        timingmask: Incomplete = ...,
        usessubscip: bool = False,
    ) -> None: ...
    def includeIISfinder(
        self,
        iisfinder: IISfinder,
        name: str,
        desc: str,
        priority: int = 10000,
        freq: int = 1,
    ) -> None: ...
    def includeNodesel(
        self,
        nodesel: Nodesel,
        name: str,
        desc: str,
        stdpriority: int,
        memsavepriority: int,
    ) -> None: ...
    def includePresol(
        self,
        presol: Presol,
        name: str,
        desc: str,
        priority: int,
        maxrounds: int,
        timing: Incomplete = ...,
    ) -> None: ...
    def includePricer(
        self,
        pricer: Pricer,
        name: str,
        desc: str,
        priority: int = 1,
        delay: bool = True,
    ) -> None: ...
    def includeProp(
        self,
        prop: Prop,
        name: str,
        desc: str,
        presolpriority: int,
        presolmaxrounds: int,
        proptiming: Incomplete,
        presoltiming: Incomplete = ...,
        priority: int = 1,
        freq: int = 1,
        delay: bool = True,
    ) -> None: ...
    def includeReader(self, reader: Reader, name: str, desc: str, ext: str) -> None: ...
    def includeRelax(
        self, relax: Relax, name: str, desc: str, priority: int = 10000, freq: int = 1
    ) -> None: ...
    def includeSepa(
        self,
        sepa: Sepa,
        name: str,
        desc: str,
        priority: int = 0,
        freq: int = 10,
        maxbounddist: float = 1.0,
        usessubscip: bool = False,
        delay: bool = False,
    ) -> None: ...
    def infinity(self) -> float: ...
    def initBendersDefault(self, subproblems: Model | dict[Any, Model]) -> None: ...
    def interruptSolve(self) -> None: ...
    def isAndConsSorted(self, and_cons: Constraint) -> bool: ...
    def isCutEfficacious(self, cut: Row, sol: Solution | None = None) -> bool: ...
    def isEQ(self, val1: float, val2: float) -> bool: ...
    def isExact(self) -> bool: ...
    def isFeasEQ(self, val1: float, val2: float) -> bool: ...
    def isFeasGE(self, val1: float, val2: float) -> bool: ...
    def isFeasGT(self, val1: float, val2: float) -> bool: ...
    def isFeasIntegral(self, value: float) -> bool: ...
    def isFeasLE(self, val1: float, val2: float) -> bool: ...
    def isFeasLT(self, val1: float, val2: float) -> bool: ...
    def isFeasNegative(self, value: float) -> bool: ...
    def isFeasPositive(self, value: float) -> bool: ...
    def isFeasZero(self, value: float) -> bool: ...
    def isGE(self, val1: float, val2: float) -> bool: ...
    def isGT(self, val1: float, val2: float) -> bool: ...
    def isHugeValue(self, val: float) -> bool: ...
    def isInfinity(self, value: float) -> bool: ...
    def isIntegral(self, value: float) -> bool: ...
    def isLE(self, val1: float, val2: float) -> bool: ...
    def isLPSolBasic(self) -> bool: ...
    def isLT(self, val1: float, val2: float) -> bool: ...
    def isNLPConstructed(self) -> bool: ...
    def isNegative(self, val: float) -> bool: ...
    def isObjChangedProbing(self) -> bool: ...
    def isObjIntegral(self) -> Incomplete: ...
    def isPositive(self, val: float) -> bool: ...
    def isReoptEnabled(self) -> bool: ...
    def isZero(self, value: float) -> bool: ...
    def lpiGetIterations(self) -> int: ...
    def markDoNotAggrVar(self, var: Variable) -> None: ...
    def markDoNotMultaggrVar(self, var: Variable) -> None: ...
    def newProbingNode(self) -> None: ...
    def optimize(self) -> None: ...
    def optimizeNogil(self) -> None: ...
    def presolve(self) -> None: ...
    def printBestSol(self, write_zeros: bool = False) -> None: ...
    def printCons(self, constraint: Constraint) -> None: ...
    def printExternalCodeVersions(self) -> None: ...
    def printNlRow(self, nlrow: NLRow) -> None: ...
    def printProblem(
        self, ext: str = ".cip", trans: bool = False, genericnames: bool = False
    ) -> None: ...
    def printRow(self, row: Row) -> None: ...
    def printSol(
        self, solution: Solution | None = None, write_zeros: bool = False
    ) -> None: ...
    def printStatistics(
        self, filename: str | os.PathLike[str] | None = None
    ) -> None: ...
    def printStatisticsJson(self) -> None: ...
    def printVersion(self) -> None: ...
    def propagateProbing(self, maxproprounds: int) -> tuple[bool, int]: ...
    def readParams(self, file: str | os.PathLike[str]) -> None: ...
    def readProblem(
        self, filename: str | os.PathLike[str], extension: str | None = None
    ) -> None: ...
    def readSol(self, filename: str | os.PathLike[str]) -> None: ...
    def readSolFile(self, filename: str | os.PathLike[str]) -> Solution: ...
    def redirectOutput(self) -> None: ...
    def relax(self) -> None: ...
    def releaseRow(self, row: Row) -> None: ...
    def repropagateNode(self, node: Node) -> None: ...
    def resetParam(self, name: str) -> None: ...
    def resetParams(self) -> None: ...
    def restartSolve(self) -> None: ...
    def separateSol(
        self,
        sol: Solution | None = None,
        pretendroot: bool = False,
        allowlocal: bool = True,
        onlydelayed: bool = False,
    ) -> tuple[bool, bool]: ...
    def setBendersSubproblemIsConvex(
        self, benders: Benders, probnumber: int, isconvex: bool = True
    ) -> None: ...
    def setBoolParam(self, name: str, value: bool) -> None: ...
    def setCharParam(self, name: str, value: str) -> None: ...
    def setCheck(self, cons: Constraint, newCheck: bool) -> None: ...
    def setEmphasis(self, paraemphasis: Incomplete, quiet: bool = True) -> None: ...
    def setEnforced(self, cons: Constraint, newEnf: bool) -> None: ...
    def setHeurTiming(self, heurname: str, heurtiming: Incomplete) -> None: ...
    def setHeuristics(self, setting: Incomplete) -> None: ...
    def setInitial(self, cons: Constraint, newInit: bool) -> None: ...
    def setIntParam(self, name: str, value: int) -> None: ...
    def setLogfile(self, path: str | None) -> None: ...
    def setLongintParam(self, name: str, value: int) -> None: ...
    def setMaximize(self) -> None: ...
    def setMinimize(self) -> None: ...
    def setModifiable(self, cons: Constraint, newMod: bool) -> None: ...
    def setObjIntegral(self) -> None: ...
    def setObjective(
        self,
        expr: Expr | SupportsFloat,
        sense: Literal["minimize", "maximize"] = "minimize",
        clear: bool | Literal["true"] = "true",  # TODO: typo?
    ) -> None: ...
    def setObjlimit(self, objlimit: float) -> None: ...
    def setParam(self, name: str, value: object) -> None: ...
    def setParams(self, params: Mapping[str, bool | float | str]) -> None: ...
    def setParamsCountsols(self) -> None: ...
    def setPresolve(self, setting: Incomplete) -> None: ...
    def setProbName(self, name: str) -> None: ...
    def setRealParam(self, name: str, value: float) -> None: ...
    def setRelaxSolVal(self, var: Variable, val: float) -> None: ...
    def setRemovable(self, cons: Constraint, newRem: bool) -> None: ...
    def setSeparating(self, setting: Incomplete) -> None: ...
    def setSolVal(self, solution: Solution, var: Variable, val: float) -> None: ...
    def setStringParam(self, name: str, value: str) -> None: ...
    def setupBendersSubproblem(
        self,
        probnumber: int,
        benders: Benders | None = None,
        solution: Solution | None = None,
        checktype: Incomplete = ...,
    ) -> None: ...
    def solveBendersSubproblem(
        self,
        probnumber: int,
        solvecip: bool,
        benders: Benders | None = None,
        solution: Solution | None = None,
    ) -> tuple[bool, float | None]: ...
    def solveConcurrent(self) -> None: ...
    def solveDiveLP(self, itlim: int = -1) -> tuple[bool, bool]: ...
    def solveProbingLP(self, itlim: int = -1) -> tuple[bool, bool]: ...
    def solveProbingLPWithPricing(
        self,
        pretendroot: Incomplete = ...,
        displayinfo: Incomplete = ...,
        maxpricerounds: Incomplete = ...,
    ) -> Incomplete: ...
    def sortAndCons(self, and_cons: Constraint) -> None: ...
    def startDive(self) -> None: ...
    def startProbing(self) -> None: ...
    def startStrongbranch(self) -> None: ...
    def tightenVarLb(
        self, var: Variable, lb: float, force: bool = False
    ) -> tuple[bool, bool]: ...
    def tightenVarLbGlobal(
        self, var: Variable, lb: float, force: bool = False
    ) -> tuple[bool, bool]: ...
    def tightenVarUb(
        self, var: Variable, ub: float, force: bool = False
    ) -> tuple[bool, bool]: ...
    def tightenVarUbGlobal(
        self, var: Variable, ub: float, force: bool = False
    ) -> tuple[bool, bool]: ...
    def to_ptr(self, give_ownership: bool) -> CapsuleType: ...
    def translateSubSol(
        self, sub_model: Model, sol: Solution, heur: Heur
    ) -> Solution: ...
    def trySol(
        self,
        solution: Solution,
        printreason: bool = True,
        completely: bool = False,
        checkbounds: bool = True,
        checkintegrality: bool = True,
        checklprows: bool = True,
        free: bool = True,
    ) -> bool: ...
    def updateBendersLowerbounds(
        self, lowerbounds: dict[int, float], benders: Benders | None = None
    ) -> None: ...
    def updateNodeLowerbound(self, node: Node, lb: float) -> None: ...
    def updateVarPseudocost(
        self, var: Variable, valdelta: float, objdelta: float, weight: float
    ) -> None: ...
    def version(self) -> float: ...
    def writeBestSol(
        self,
        filename: str | bytes | os.PathLike[AnyStr] = "origprob.sol",
        write_zeros: bool = False,
    ) -> None: ...
    def writeBestTransSol(
        self,
        filename: str | bytes | os.PathLike[AnyStr] = "transprob.sol",
        write_zeros: bool = False,
    ) -> None: ...
    def writeLP(self, filename: str | os.PathLike[str] = "LP.lp") -> None: ...
    def writeMIP(
        self,
        filename: str | os.PathLike[str],
        genericnames: bool = False,
        origobj: bool = False,
        lazyconss: bool = False,
    ) -> None: ...
    def writeName(self, var: Variable) -> None: ...
    def writeParams(
        self,
        filename: str | os.PathLike[str] = "param.set",
        comments: bool = True,
        onlychanged: bool = True,
        verbose: bool = True,
    ) -> None: ...
    def writeProblem(
        self,
        filename: str | os.PathLike[str] = "model.cip",
        trans: bool = False,
        genericnames: bool = False,
        verbose: bool = True,
    ) -> None: ...
    def writeSol(
        self,
        solution: Solution,
        filename: str | bytes | os.PathLike[AnyStr] = "origprob.sol",
        write_zeros: bool = False,
    ) -> None: ...
    def writeStatistics(
        self, filename: str | bytes | os.PathLike[AnyStr] = "origprob.stats"
    ) -> None: ...
    def writeStatisticsJson(
        self, filename: str | os.PathLike[str] = "origprob.stats.json"
    ) -> None: ...
    def writeTransSol(
        self,
        solution: Solution,
        filename: str | bytes | os.PathLike[AnyStr] = "transprob.sol",
        write_zeros: bool = False,
    ) -> None: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class NLRow:
    data: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def getConstant(self) -> Incomplete: ...
    def getDualsol(self) -> Incomplete: ...
    def getLhs(self) -> Incomplete: ...
    def getLinearTerms(self) -> Incomplete: ...
    def getRhs(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class Node:
    data: Incomplete
    def __init__(self) -> None: ...
    def getAddedConss(self) -> Incomplete: ...
    def getDepth(self) -> Incomplete: ...
    def getDomchg(self) -> Incomplete: ...
    def getEstimate(self) -> Incomplete: ...
    def getLowerbound(self) -> Incomplete: ...
    def getNAddedConss(self) -> Incomplete: ...
    def getNDomchg(self) -> Incomplete: ...
    def getNParentBranchings(self) -> Incomplete: ...
    def getNumber(self) -> Incomplete: ...
    def getParent(self) -> Incomplete: ...
    def getParentBranchings(self) -> Incomplete: ...
    def getType(self) -> Incomplete: ...
    def isActive(self) -> Incomplete: ...
    def isPropagatedAgain(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class Nodesel:
    model: Incomplete
    def __init__(self) -> None: ...
    def nodecomp(self, node1: Incomplete, node2: Incomplete) -> Incomplete: ...
    def nodeexit(self) -> Incomplete: ...
    def nodeexitsol(self) -> Incomplete: ...
    def nodefree(self) -> Incomplete: ...
    def nodeinit(self) -> Incomplete: ...
    def nodeinitsol(self) -> Incomplete: ...
    def nodeselect(self) -> Incomplete: ...

class Op:
    add: ClassVar[str] = ...
    const: ClassVar[str] = ...
    cos: ClassVar[str] = ...
    div: ClassVar[str] = ...
    exp: ClassVar[str] = ...
    fabs: ClassVar[str] = ...
    log: ClassVar[str] = ...
    minus: ClassVar[str] = ...
    mul: ClassVar[str] = ...
    plus: ClassVar[str] = ...
    power: ClassVar[str] = ...
    prod: ClassVar[str] = ...
    sin: ClassVar[str] = ...
    sqrt: ClassVar[str] = ...
    varidx: ClassVar[str] = ...

class PY_SCIP_BENDERSENFOTYPE:
    CHECK: ClassVar[int] = ...
    LP: ClassVar[int] = ...
    PSEUDO: ClassVar[int] = ...
    RELAX: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_BRANCHDIR:
    AUTO: ClassVar[int] = ...
    DOWNWARDS: ClassVar[int] = ...
    FIXED: ClassVar[int] = ...
    UPWARDS: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_EVENTTYPE:
    BESTSOLFOUND: ClassVar[int] = ...
    BOUNDCHANGED: ClassVar[int] = ...
    BOUNDRELAXED: ClassVar[int] = ...
    BOUNDTIGHTENED: ClassVar[int] = ...
    DISABLED: ClassVar[int] = ...
    DOMCHANGED: ClassVar[int] = ...
    DUALBOUNDIMPROVED: ClassVar[int] = ...
    FIRSTLPSOLVED: ClassVar[int] = ...
    GAPUPDATED: ClassVar[int] = ...
    GBDCHANGED: ClassVar[int] = ...
    GHOLEADDED: ClassVar[int] = ...
    GHOLECHANGED: ClassVar[int] = ...
    GHOLEREMOVED: ClassVar[int] = ...
    GLBCHANGED: ClassVar[int] = ...
    GUBCHANGED: ClassVar[int] = ...
    HOLECHANGED: ClassVar[int] = ...
    IMPLADDED: ClassVar[int] = ...
    LBCHANGED: ClassVar[int] = ...
    LBRELAXED: ClassVar[int] = ...
    LBTIGHTENED: ClassVar[int] = ...
    LHOLEADDED: ClassVar[int] = ...
    LHOLECHANGED: ClassVar[int] = ...
    LHOLEREMOVED: ClassVar[int] = ...
    LPEVENT: ClassVar[int] = ...
    LPSOLVED: ClassVar[int] = ...
    NODEBRANCHED: ClassVar[int] = ...
    NODEDELETE: ClassVar[int] = ...
    NODEEVENT: ClassVar[int] = ...
    NODEFEASIBLE: ClassVar[int] = ...
    NODEFOCUSED: ClassVar[int] = ...
    NODEINFEASIBLE: ClassVar[int] = ...
    NODESOLVED: ClassVar[int] = ...
    OBJCHANGED: ClassVar[int] = ...
    POORSOLFOUND: ClassVar[int] = ...
    PRESOLVEROUND: ClassVar[int] = ...
    ROWADDEDLP: ClassVar[int] = ...
    ROWADDEDSEPA: ClassVar[int] = ...
    ROWCHANGED: ClassVar[int] = ...
    ROWCOEFCHANGED: ClassVar[int] = ...
    ROWCONSTCHANGED: ClassVar[int] = ...
    ROWDELETEDLP: ClassVar[int] = ...
    ROWDELETEDSEPA: ClassVar[int] = ...
    ROWEVENT: ClassVar[int] = ...
    ROWSIDECHANGED: ClassVar[int] = ...
    SOLEVENT: ClassVar[int] = ...
    SOLFOUND: ClassVar[int] = ...
    SYNC: ClassVar[int] = ...
    UBCHANGED: ClassVar[int] = ...
    UBRELAXED: ClassVar[int] = ...
    UBTIGHTENED: ClassVar[int] = ...
    VARADDED: ClassVar[int] = ...
    VARCHANGED: ClassVar[int] = ...
    VARDELETED: ClassVar[int] = ...
    VAREVENT: ClassVar[int] = ...
    VARFIXED: ClassVar[int] = ...
    VARUNLOCKED: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_HEURTIMING:
    AFTERLPLOOP: ClassVar[int] = ...
    AFTERLPNODE: ClassVar[int] = ...
    AFTERLPPLUNGE: ClassVar[int] = ...
    AFTERPROPLOOP: ClassVar[int] = ...
    AFTERPSEUDONODE: ClassVar[int] = ...
    AFTERPSEUDOPLUNGE: ClassVar[int] = ...
    BEFORENODE: ClassVar[int] = ...
    BEFOREPRESOL: ClassVar[int] = ...
    DURINGLPLOOP: ClassVar[int] = ...
    DURINGPRESOLLOOP: ClassVar[int] = ...
    DURINGPRICINGLOOP: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_IMPLINTTYPE:
    NONE: ClassVar[int] = ...
    STRONG: ClassVar[int] = ...
    WEAK: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_LOCKTYPE:
    CONFLICT: ClassVar[int] = ...
    MODEL: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_BASESTAT:
    LOWER: ClassVar[int] = ...
    BASIC: ClassVar[int] = ...
    UPPER: ClassVar[int] = ...
    ZERO: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_LPPARAM:
    BARRIERCONVTOL: ClassVar[int] = ...
    CONDITIONLIMIT: ClassVar[int] = ...
    DUALFEASTOL: ClassVar[int] = ...
    FASTMIP: ClassVar[int] = ...
    FEASTOL: ClassVar[int] = ...
    FROMSCRATCH: ClassVar[int] = ...
    LPINFO: ClassVar[int] = ...
    LPITLIM: ClassVar[int] = ...
    LPTILIM: ClassVar[int] = ...
    MARKOWITZ: ClassVar[int] = ...
    OBJLIM: ClassVar[int] = ...
    POLISHING: ClassVar[int] = ...
    PRESOLVING: ClassVar[int] = ...
    PRICING: ClassVar[int] = ...
    RANDOMSEED: ClassVar[int] = ...
    REFACTOR: ClassVar[int] = ...
    ROWREPSWITCH: ClassVar[int] = ...
    SCALING: ClassVar[int] = ...
    THREADS: ClassVar[int] = ...
    TIMING: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_LPSOLSTAT:
    ERROR: ClassVar[int] = ...
    INFEASIBLE: ClassVar[int] = ...
    ITERLIMIT: ClassVar[int] = ...
    NOTSOLVED: ClassVar[int] = ...
    OBJLIMIT: ClassVar[int] = ...
    OPTIMAL: ClassVar[int] = ...
    TIMELIMIT: ClassVar[int] = ...
    UNBOUNDEDRAY: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_NODETYPE:
    CHILD: ClassVar[int] = ...
    DEADEND: ClassVar[int] = ...
    FOCUSNODE: ClassVar[int] = ...
    FORK: ClassVar[int] = ...
    JUNCTION: ClassVar[int] = ...
    LEAF: ClassVar[int] = ...
    PROBINGNODE: ClassVar[int] = ...
    PSEUDOFORK: ClassVar[int] = ...
    REFOCUSNODE: ClassVar[int] = ...
    SIBLING: ClassVar[int] = ...
    SUBROOT: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_PARAMEMPHASIS:
    BENCHMARK: ClassVar[int] = ...
    COUNTER: ClassVar[int] = ...
    CPSOLVER: ClassVar[int] = ...
    DEFAULT: ClassVar[int] = ...
    EASYCIP: ClassVar[int] = ...
    FEASIBILITY: ClassVar[int] = ...
    HARDLP: ClassVar[int] = ...
    NUMERICS: ClassVar[int] = ...
    OPTIMALITY: ClassVar[int] = ...
    PHASEFEAS: ClassVar[int] = ...
    PHASEIMPROVE: ClassVar[int] = ...
    PHASEPROOF: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_PARAMSETTING:
    AGGRESSIVE: ClassVar[int] = ...
    DEFAULT: ClassVar[int] = ...
    FAST: ClassVar[int] = ...
    OFF: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_PRESOLTIMING:
    EXHAUSTIVE: ClassVar[int] = ...
    FAST: ClassVar[int] = ...
    MEDIUM: ClassVar[int] = ...
    NONE: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_PROPTIMING:
    AFTERLPLOOP: ClassVar[int] = ...
    AFTERLPNODE: ClassVar[int] = ...
    BEFORELP: ClassVar[int] = ...
    DURINGLPLOOP: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_RESULT:
    BRANCHED: ClassVar[int] = ...
    CONSADDED: ClassVar[int] = ...
    CONSCHANGED: ClassVar[int] = ...
    CUTOFF: ClassVar[int] = ...
    DELAYED: ClassVar[int] = ...
    DIDNOTFIND: ClassVar[int] = ...
    DIDNOTRUN: ClassVar[int] = ...
    FEASIBLE: ClassVar[int] = ...
    FOUNDSOL: ClassVar[int] = ...
    INFEASIBLE: ClassVar[int] = ...
    NEWROUND: ClassVar[int] = ...
    REDUCEDDOM: ClassVar[int] = ...
    SEPARATED: ClassVar[int] = ...
    SOLVELP: ClassVar[int] = ...
    SUCCESS: ClassVar[int] = ...
    SUSPENDED: ClassVar[int] = ...
    UNBOUNDED: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_ROWORIGINTYPE:
    CONS: ClassVar[int] = ...
    REOPT: ClassVar[int] = ...
    SEPA: ClassVar[int] = ...
    UNSPEC: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_SOLORIGIN:
    LPSOL: ClassVar[int] = ...
    NLPSOL: ClassVar[int] = ...
    ORIGINAL: ClassVar[int] = ...
    PARTIAL: ClassVar[int] = ...
    PSEUDOSOL: ClassVar[int] = ...
    RELAXSOL: ClassVar[int] = ...
    UNKNOWN: ClassVar[int] = ...
    ZERO: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_STAGE:
    EXITPRESOLVE: ClassVar[int] = ...
    EXITSOLVE: ClassVar[int] = ...
    FREE: ClassVar[int] = ...
    FREETRANS: ClassVar[int] = ...
    INIT: ClassVar[int] = ...
    INITPRESOLVE: ClassVar[int] = ...
    INITSOLVE: ClassVar[int] = ...
    PRESOLVED: ClassVar[int] = ...
    PRESOLVING: ClassVar[int] = ...
    PROBLEM: ClassVar[int] = ...
    SOLVED: ClassVar[int] = ...
    SOLVING: ClassVar[int] = ...
    TRANSFORMED: ClassVar[int] = ...
    TRANSFORMING: ClassVar[int] = ...
    def __init__(self) -> None: ...

class PY_SCIP_STATUS:
    BESTSOLLIMIT: ClassVar[int] = ...
    DUALLIMIT: ClassVar[int] = ...
    GAPLIMIT: ClassVar[int] = ...
    INFEASIBLE: ClassVar[int] = ...
    INFORUNBD: ClassVar[int] = ...
    MEMLIMIT: ClassVar[int] = ...
    NODELIMIT: ClassVar[int] = ...
    OPTIMAL: ClassVar[int] = ...
    PRIMALLIMIT: ClassVar[int] = ...
    RESTARTLIMIT: ClassVar[int] = ...
    SOLLIMIT: ClassVar[int] = ...
    STALLNODELIMIT: ClassVar[int] = ...
    TIMELIMIT: ClassVar[int] = ...
    TOTALNODELIMIT: ClassVar[int] = ...
    UNBOUNDED: ClassVar[int] = ...
    UNKNOWN: ClassVar[int] = ...
    USERINTERRUPT: ClassVar[int] = ...
    def __init__(self) -> None: ...

@disjoint_base
class PowExpr(GenExpr):
    expo: Incomplete
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

@disjoint_base
class Presol:
    model: Incomplete
    def __init__(self) -> None: ...
    def presolexec(
        self, nrounds: Incomplete, presoltiming: Incomplete
    ) -> Incomplete: ...
    def presolexit(self) -> Incomplete: ...
    def presolexitpre(self) -> Incomplete: ...
    def presolfree(self) -> Incomplete: ...
    def presolinit(self) -> Incomplete: ...
    def presolinitpre(self) -> Incomplete: ...

@disjoint_base
class Pricer:
    model: Incomplete
    def __init__(self) -> None: ...
    def pricerexit(self) -> Incomplete: ...
    def pricerexitsol(self) -> Incomplete: ...
    def pricerfarkas(self) -> Incomplete: ...
    def pricerfree(self) -> Incomplete: ...
    def pricerinit(self) -> Incomplete: ...
    def pricerinitsol(self) -> Incomplete: ...
    def pricerredcost(self) -> Incomplete: ...

@disjoint_base
class ProdExpr(GenExpr):
    constant: Incomplete
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

@disjoint_base
class Prop:
    model: Incomplete
    def __init__(self) -> None: ...
    def propexec(self, proptiming: Incomplete) -> Incomplete: ...
    def propexit(self) -> Incomplete: ...
    def propexitpre(self) -> Incomplete: ...
    def propexitsol(self, restart: Incomplete) -> Incomplete: ...
    def propfree(self) -> Incomplete: ...
    def propinit(self) -> Incomplete: ...
    def propinitpre(self) -> Incomplete: ...
    def propinitsol(self) -> Incomplete: ...
    def proppresol(
        self, nrounds: Incomplete, presoltiming: Incomplete, result_dict: Incomplete
    ) -> Incomplete: ...
    def propresprop(
        self,
        confvar: Incomplete,
        inferinfo: Incomplete,
        bdtype: Incomplete,
        relaxedbd: Incomplete,
    ) -> Incomplete: ...

@disjoint_base
class Reader:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def readerfree(self) -> Incomplete: ...
    def readerread(self, filename: Incomplete) -> Incomplete: ...
    def readerwrite(
        self,
        file: Incomplete,
        name: Incomplete,
        transformed: Incomplete,
        objsense: Incomplete,
        objoffset: Incomplete,
        objscale: Incomplete,
        binvars: Incomplete,
        intvars: Incomplete,
        implvars: Incomplete,
        contvars: Incomplete,
        fixedvars: Incomplete,
        startnvars: Incomplete,
        conss: Incomplete,
        maxnconss: Incomplete,
        startnconss: Incomplete,
        genericnames: Incomplete,
    ) -> Incomplete: ...

@disjoint_base
class Relax:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def relaxexec(self) -> Incomplete: ...
    def relaxexit(self) -> Incomplete: ...
    def relaxexitsol(self) -> Incomplete: ...
    def relaxfree(self) -> Incomplete: ...
    def relaxinit(self) -> Incomplete: ...
    def relaxinitsol(self) -> Incomplete: ...

@disjoint_base
class Row:
    data: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def getAge(self) -> Incomplete: ...
    def getBasisStatus(self) -> Incomplete: ...
    def getCols(self) -> Incomplete: ...
    def getConsOriginConshdlrtype(self) -> Incomplete: ...
    def getConstant(self) -> Incomplete: ...
    def getDualfarkas(self) -> Incomplete: ...
    def getDualsol(self) -> Incomplete: ...
    def getLPPos(self) -> Incomplete: ...
    def getLhs(self) -> Incomplete: ...
    def getNLPNonz(self) -> Incomplete: ...
    def getNNonz(self) -> Incomplete: ...
    def getNorm(self) -> Incomplete: ...
    def getOrigintype(self) -> Incomplete: ...
    def getRhs(self) -> Incomplete: ...
    def getVals(self) -> Incomplete: ...
    def isInGlobalCutpool(self) -> Incomplete: ...
    def isIntegral(self) -> Incomplete: ...
    def isLocal(self) -> Incomplete: ...
    def isModifiable(self) -> Incomplete: ...
    def isRemovable(self) -> Incomplete: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@disjoint_base
class RowExact:
    data: Incomplete
    def __init__(self) -> None: ...

@disjoint_base
class Sepa:
    model: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def sepaexeclp(self) -> Incomplete: ...
    def sepaexecsol(self, solution: Incomplete) -> Incomplete: ...
    def sepaexit(self) -> Incomplete: ...
    def sepaexitsol(self) -> Incomplete: ...
    def sepafree(self) -> Incomplete: ...
    def sepainit(self) -> Incomplete: ...
    def sepainitsol(self) -> Incomplete: ...

@disjoint_base
class Solution:
    data: Incomplete
    def __init__(self, raise_error: Incomplete = ...) -> None: ...
    def _checkStage(self, method: Incomplete) -> Incomplete: ...
    def getOrigin(self) -> Incomplete: ...
    def retransform(self) -> Incomplete: ...
    def translate(self, target: Incomplete) -> Incomplete: ...
    def __getitem__(self, index: Incomplete, /) -> Incomplete: ...
    def __setitem__(self, key: Incomplete, value: Incomplete, /) -> None: ...

class Statistics:
    status: str
    total_time: float
    solving_time: float
    presolving_time: float
    reading_time: float
    copying_time: float
    problem_name: str
    presolved_problem_name: str
    n_runs: int | None
    n_nodes: int | None
    n_solutions_found: int
    first_solution: float | None
    primal_bound: float | None
    dual_bound: float | None
    gap: float | None
    primal_dual_integral: float | None
    def __init__(
        self,
        status: str,
        total_time: float,
        solving_time: float,
        presolving_time: float,
        reading_time: float,
        copying_time: float,
        problem_name: str,
        presolved_problem_name: str,
        n_runs: int | None,
        n_nodes: int | None,
        n_solutions_found: int,
        first_solution: float | None,
        primal_bound: float | None,
        dual_bound: float | None,
        gap: float | None,
        primal_dual_integral: float | None,
    ) -> None: ...
    @property
    def n_binary_vars(self) -> int: ...
    @property
    def n_conss(self) -> int: ...
    @property
    def n_continuous_vars(self) -> int: ...
    @property
    def n_implicit_integer_vars(self) -> int: ...
    @property
    def n_integer_vars(self) -> int: ...
    @property
    def n_maximal_cons(self) -> int: ...
    @property
    def n_presolved_binary_vars(self) -> int: ...
    @property
    def n_presolved_conss(self) -> int: ...
    @property
    def n_presolved_continuous_vars(self) -> int: ...
    @property
    def n_presolved_implicit_integer_vars(self) -> int: ...
    @property
    def n_presolved_integer_vars(self) -> int: ...
    @property
    def n_presolved_maximal_cons(self) -> int: ...
    @property
    def n_presolved_vars(self) -> int: ...
    @property
    def n_vars(self) -> int: ...
    def __replace__(self, **changes: Incomplete) -> Statistics: ...

@disjoint_base
class SumExpr(GenExpr):
    coefs: Incomplete
    constant: Incomplete
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

@disjoint_base
class Term:
    vartuple: Incomplete
    def __init__(self, *vartuple: Incomplete) -> None: ...
    def __mul__(self, other: Term, /) -> Term: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __getitem__(self, index: Incomplete, /) -> Incomplete: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

class UnaryExpr(GenExpr):
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...
    def __abs__(self) -> GenExpr: ...

@disjoint_base
class VarExpr(GenExpr):
    var: Incomplete
    def __init__(self, *args: Incomplete, **kwargs: Incomplete) -> None: ...

@disjoint_base
class Variable(Expr):
    data: Incomplete
    name: Incomplete
    def __init__(self) -> None: ...
    def getAvgSol(self) -> Incomplete: ...
    def getCol(self) -> Incomplete: ...
    def getImplType(self) -> Incomplete: ...
    def getIndex(self) -> Incomplete: ...
    def getLPSol(self) -> Incomplete: ...
    def getLbGlobal(self) -> Incomplete: ...
    def getLbLocal(self) -> Incomplete: ...
    def getLbOriginal(self) -> Incomplete: ...
    def getNBranchings(self, branchdir: Incomplete) -> Incomplete: ...
    def getNBranchingsCurrentRun(self, branchdir: Incomplete) -> Incomplete: ...
    def getNLocksDown(self) -> Incomplete: ...
    def getNLocksDownType(self, locktype: Incomplete) -> Incomplete: ...
    def getNLocksUp(self) -> Incomplete: ...
    def getNLocksUpType(self, locktype: Incomplete) -> Incomplete: ...
    def getObj(self) -> Incomplete: ...
    def getStatus(self) -> Incomplete: ...
    def getUbGlobal(self) -> Incomplete: ...
    def getUbLocal(self) -> Incomplete: ...
    def getUbOriginal(self) -> Incomplete: ...
    def isActive(self) -> Incomplete: ...
    def isBinary(self) -> Incomplete: ...
    def isDeletable(self) -> Incomplete: ...
    def isImpliedIntegral(self) -> Incomplete: ...
    def isInLP(self) -> Incomplete: ...
    def isIntegral(self) -> Incomplete: ...
    def isNonImpliedIntegral(self) -> Incomplete: ...
    def isOriginal(self) -> Incomplete: ...
    def isRelaxationOnly(self) -> Incomplete: ...
    def markRelaxationOnly(self) -> Incomplete: ...
    def ptr(self) -> Incomplete: ...
    def varMayRound(self, direction: Incomplete = ...) -> Incomplete: ...
    def vtype(self) -> Incomplete: ...

@disjoint_base
class _VarArray:
    def __init__(self) -> None: ...
