from pyscipopt import Constraint as Constraint, Model as Model

def getLocalConss(model: Model, node=None) -> list[list[Constraint]]: ...
def getNLocalConss(model: Model, node=None) -> list[int]: ...
